### ISSUE TITLE
YES THIS IS JUST WHAT I WAS LOOKING FOR

### ISSUE THREAD

**Issue by geelen** [jrnewton/github-readme-to-html#8]
Sorry for shouting, but I _really_ didn't want to have to build something like this. Glad I found it!!

**Comment by jrnewton** [comment]
Ha! Glad you like it 😁

On August 4, 2022, Yasas Munasinghe De Silva ***@***.***>
wrote:
> Sorry for shouting, but I really didn't want to have to build
> something like this. Glad I found it!!
>

—
Reply to this email directly, view it on GitHub
<https://github.com/jrnewton/github-readme-to-html/issues/8>, or
unsubscribe <https://github.com/notifications/unsubscribe-
auth/AIPLNAHLQK56WEAKS33MZH3VXOWXTANCNFSM55SJHJJA>.
You are receiving this because you are subscribed to this thread.Message
ID: ***@***.***>
